- hosts: all
  tasks:
  - name: Update APT to be sure we are using latest repositories
    become: true
    apt:
      update_cache:

  - name: Upgrade system
    become: true
    apt:
      upgrade: dist
    notify: reboot server

  - name: Install some packages
    become: true
    apt:
      name: ['wget', 'vim', 'git', 'build-essential']

  - name: Install Maven
    become: true
    apt:
      name: maven
      state: present

  - name: Install OpenJDK Java 11
    become: true
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Download OpenJFX 17
    get_url:
      url: "https://gluonhq.com/download/javafx-17-ea-sdk-linux-arm32/"
      dest: "/home/pi/openjfx.zip"

  - name: Extract OpenJFX 17
    become: true
    unarchive:
      src: "/home/pi/openjfx.zip"
      dest: "/opt/"
      mode: 0755

  - name: Install Visual Studio Code
    become: true
    apt:
      name: code
      state: present

  handlers:
    - name: reboot server
      become: true
      reboot:
