- hosts: all
  tasks:
  - name: Update APT to be sure we are using latest repositories
    become: true
    apt:
      update_cache:

  - name: Install Maven
      become: yes
      apt:
        name: maven
        state: present

  - name: Install OpenJDK Java 11
    become: yes
    apt:
      name: openjdk-11-jre
      state: present

  - name: Download and extract OpenJFX 16
    become: yes
    tags: javafxdownload
    unarchive:
      src: "https://gluonhq.com/download/javafx-linux-arm32-drm-sdk/"
      dest: "/opt/"
      mode: 0755
      remote_src: yes

  - name: Install XServer to be able to run JavaFX application in kiosk mode
    become: yes
    apt:
      name: ['xserver-xorg','x11-xserver-utils','xinit','lightdm','openbox']
      state: present

  - name: Reboot
    become: yes
    reboot:


