# This Ansible script needs to be used on a "server" OS, which doesn't have a desktop environment,
#    e.g. "Raspberry Pi OS Lite"
- hosts: all
  tasks:
  - name: Update APT to be sure we are using latest repositories
    become: true
    apt:
      update_cache:

  - name: Upgrade system
    become: true
    apt:
      upgrade: dist
    notify: reboot server

  - name: Install some packages
    become: true
    apt:
      name: ['wget', 'vim', 'git', 'build-essential']

  - name: Install Maven
    become: true
    apt:
      name: maven
      state: present

  - name: Install OpenJDK Java 11
    become: true
    apt:
      name: openjdk-11-jre
      state: present

  - name: Download and extract OpenJFX 16
    become: true
    tags: javafxdownload
    unarchive:
      src: "https://gluonhq.com/download/javafx-17-ea-sdk-linux-arm32/"
      dest: "/opt/"
      mode: 0755
      remote_src: true
    notify: reboot server

  - name: Rename the unpacked JavaFX 17 directory to consistently use the same location across projects
    become: true
    command: rm -rf /opt/arm32fb-sdk/ ; mv /opt/javafx-sdk-17/ /opt/arm32fb-sdk/
    notify: reboot server

  - name: Install XServer to be able to run JavaFX application in kiosk mode
    become: yes
    apt:
      name: ['xserver-xorg','x11-xserver-utils','xinit','lightdm','openbox']
      state: present
    notify: reboot server

  - name: Automatic login
    become: yes
    command: "raspi-config nonint do_boot_behaviour B4"
    notify: reboot server

  handlers:
    - name: reboot server
      become: true
      reboot:
