- hosts: all
  tasks:
  - name: Download and extract OpenJFX
    become: true
    tags: javafxdownload
    unarchive:
      src: "https://gluonhq.com/download/javafx-17-ea-sdk-linux-arm32/"
      dest: "/opt/"
      mode: 0755
      remote_src: true

  - name: Rename the unpacked JavaFX 17 directory to consistently use the same location across projects
    become: true
    command: mv /opt/javafx-sdk-17/ /opt/arm32fb-sdk/
