- hosts: all
  tasks:
  - name: Download and extract OpenJFX
    become: true
    tags: javafxdownload
    unarchive:
      src: "https://gluonhq.com/download/javafx-linux-arm32-drm-sdk/"
      dest: "/opt/"
      mode: 0755
      remote_src: true
